import { buildMediaTree } from "./utilities.js";
import secretConfig from "./secret.config.js";
import express from "express";

let mediaTree = [];
const init = async () => {
  mediaTree = await buildMediaTree(mediaTree);
  // console.dir(mediaTree, { depth: 5 });
};
init();

// --------------- Server ---------------------
const app = express();

// serve static files
app.use(express.static("public"));

// API
app.get("/dirtree", async (req, res) => {
  // Give the high-level psuedo folders if no path provided.
  if (!req.query.path) {
    return res.json({
      files: mediaTree.map(({ children, ...rest }) => rest),
      parent: null,
    });
  }
  let files = [];
  const parts = req.query.path.split("/").filter(Boolean);
  console.log("parts: ", parts);
  let current = { children: mediaTree };
  for (const part of parts) {
    current = current.children?.find((c) => c.name === part);
    if (!current || !current.children) {
      console.error("Path part not found or empty: ", part);
      return res.json({ files: [], parent: null, error: true });
    }
  }
  const parent = parts.length > 1 ? parts.slice(0, -1).join("/") : null;
  files = current.children.map(({ children, ...rest }) => rest);
  res.json({ files, parent });
});

// Files
app.get("/file", async (req, res) => {
  const parts = req.query.path.split("/").filter(Boolean);
  let current = { children: mediaTree };
  for (const part of parts) {
    current = current.children?.find((c) => c.name === part);
    if (!current) {
      console.error("Path part not found or empty: ", part);
      return res.json({ msg: "File not found." });
    }
  }
  res.sendFile(current.path);
});

app.listen(secretConfig.port, () => {
  console.log(`Server running on http://localhost:${secretConfig.port}`);
});

/*
//////////////////////////////////////////////////////////////////////////////////

// // Get the file data providing a relative path.
// app.get("/subtitles", (req, res) => {
//   const filePath = path.join(rootPath, req.query.path);
//   fsp.access(filePath, fsp.constants.F_OK, (err) => {
//     if (err) {
//       return res.status(404).send("Subtitles file not found");
//     }
//     res.sendFile(filePath, (err) => {
//       if (err) {
//         res.status(500).send("Error getting subtitles file data");
//       }
//     });
//   });
// });

// // Stream video files (this function was generated by ChatGPT)
// app.get("/video", async (req, res) => {
//   const videoType = req.query.type;
//   let rootPath;
//   if (videoType === "movie") rootPath = rootPathMovies;
//   else if (videoType === "series") rootPath = rootPathSeries;
//   const videoPath = path.join(rootPath, req.query.path + "/");
//   let videoFileName = "";
//   const files = await fsp.readdir(videoPath);
//   files.forEach(function (file) {
//     console.log("File: ", file);
//     const fileExt = file.split(".").at(-1);
//     if (config.fileTypes.video.includes(fileExt)) {
//       videoFileName = file;
//     }
//   });
//   const fullVideoPath = path.join(videoPath, videoFileName);
//   await fsp.access(fullVideoPath);
//   const stat = await fsp.stat(fullVideoPath);
//   const fileSize = stat.size;
//   const range = req.headers.range;
//   if (range) {
//     const parts = range.replace(/bytes=/, "").split("-");
//     const start = parseInt(parts[0], 10);
//     const end = parts[1] ? parseInt(parts[1], 10) : fileSize - 1;
//     if (start >= fileSize) {
//       res
//         .status(416)
//         .send("Requested range not satisfiable\n" + start + " >= " + fileSize);
//       return;
//     }
//     const chunkSize = end - start + 1;
//     const file = fs.createReadStream(fullVideoPath, { start, end });
//     const head = {
//       "Content-Range": `bytes ${start}-${end}/${fileSize}`,
//       "Accept-Ranges": "bytes",
//       "Content-Length": chunkSize,
//       "Content-Type": "video/mp4",
//     };
//     res.writeHead(206, head);
//     file.pipe(res);
//   } else {
//     const head = {
//       "Content-Length": fileSize,
//       "Content-Type": "video/mp4",
//     };
//     res.writeHead(200, head);
//     fs.createReadStream(fullVideoPath).pipe(res);
//   }
// });

app.get("/favicon.ico", (req, res) => {
  res.type("image/x-icon");
  res.sendFile(path.join(__dirname, "/public/images/favicons/favicon.ico"));
});

// app.use("/", express.static(__dirname + "/public"));

// app.listen(config.port, function () {
//   console.log(`Video streaming server running on port ${config.port}...`);
// });
*/
